### ISSUE TITLE
Can kNVSE animations be in a BSA?

### ISSUE THREAD

**Issue by poperigby** [korri123/kNVSE#2]
Hi, I was wondering, is it possible for kNVSE animations to work when they're packaged in a BSA? From what I can tell, it doesn't seem to be possible, because when I package them into a BSA, they won't load in-game. I just wanted to get confirmation on this.

If this is the case, are there any specific directories that can't be packaged, besides `Meshes/AnimGroupOverride`?

Thanks!

**Comment by korri123** [comment]
Nope, this is not currently possible unfortunately. AFAIK `Meshes/AnimGroupOverride` is the only directory that can't be packaged like this besides maybe JIP script runner scripts but I'm not sure about those.

**Comment by poperigby** [comment]
Thank you for confirming!
